/*
 * Copyright (c) 2022-2026  Moddable Tech, Inc.
 *
 *   This file is part of the Moddable SDK Tools.
 *
 *   The Moddable SDK Tools is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   The Moddable SDK Tools is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with the Moddable SDK Tools.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
	xsdb: the command line xsbug. Listens for debuggees, launches the one named on the command line,
	and routes the prompt to the active machine. Ported from tools/xsbug-log (Node) to XS.
	Portions, particularly xsdbRouter, generated by Claude Code and Google Antigravity. Beware.
*/

import { Socket, Listener } from "socket";
import { File } from "file";
import Timer from "timer";
import Host from "host";
import { LineEditor } from "lineeditor";
import { Machine } from "machine";
import { LogMachine } from "debugmachine";

globalThis.console = {
	log(...args) {
		Host.write(args.map(String).join(" "), "\n");
	}
};

const portIn = Number.parseInt(Host.getenv("XSBUG_LOG_PORT") || "5002");
if (!(portIn > 0 && portIn < 65536)) {
	console.log(`xsdb: XSBUG_LOG_PORT is "${Host.getenv("XSBUG_LOG_PORT")}", not a port number. Exiting.`);
	Host.exit(1);
}
let connections = 0;
let autoexit = false;
let child = null;

const xsdbRouter = {
	machines: [],
	activeThreadId: 0,
	nextThreadId: 1,
	showMcsim: false,

	prefsPath() {
		try { return Host.join(Host.getenv("XSBUG_PROJECT") || Host.cwd(), ".xsdb.json"); } catch (e) { return null; }
	},
	loadPrefs() {
		try {
			const p = this.prefsPath();
			if (p && File.exists(p)) {
				const file = new File(p);
				const data = JSON.parse(file.read(String));
				file.close();
				if (data.showMcsim !== undefined) this.showMcsim = data.showMcsim;
				if (data.outputFormat !== undefined) this.globalOutputFormat = data.outputFormat;
				if (data.exceptionsMode !== undefined) this.globalExceptionsMode = data.exceptionsMode;
				if (data.breakOnStart !== undefined) this.globalBreakOnStart = data.breakOnStart;
				if (data.timestamps !== undefined) this.globalTimestamps = data.timestamps;
				if (Array.isArray(data.breakpoints)) this.globalBreakpoints = data.breakpoints;
				if (data.breakpointIdCounter !== undefined) this.globalBreakpointIdCounter = data.breakpointIdCounter;
			}
		} catch (e) {}
		this.globalBreakOnStart = this.globalBreakOnStart ?? false;
		this.globalExceptionsMode = this.globalExceptionsMode ?? 'off';
		this.globalOutputFormat = this.globalOutputFormat ?? 'text';
		this.globalTimestamps = this.globalTimestamps ?? 'off';
		this.globalBreakpoints = this.globalBreakpoints ?? [];
		if (this.globalBreakpointIdCounter === undefined) {
			this.globalBreakpointIdCounter = 0;
			this.globalBreakpoints.forEach(bp => {
				if (bp.id === undefined) bp.id = ++this.globalBreakpointIdCounter;
				else this.globalBreakpointIdCounter = Math.max(this.globalBreakpointIdCounter, bp.id);
			});
		}
	},
	savePrefs() {
		try {
			const p = this.prefsPath();
			if (p) {
				if (this.globalBreakpoints && this.globalBreakpoints.length === 0)
					this.globalBreakpointIdCounter = 0;

				File.delete(p);
				const file = new File(p, true);
				file.write(JSON.stringify({
					showMcsim: this.showMcsim,
					outputFormat: this.globalOutputFormat,
					exceptionsMode: this.globalExceptionsMode,
					breakOnStart: this.globalBreakOnStart,
					timestamps: this.globalTimestamps,
					breakpoints: this.globalBreakpoints,
					breakpointIdCounter: this.globalBreakpointIdCounter
				}));
				file.close();
			}
		} catch (e) {}
	},

	isHidden(m) {
		return m && !m.interactive && !this.showMcsim;
	},

	getMachine(id) {
		return this.machines.find(m => m && m.id === id) || null;
	},

	init() {
		this.loadPrefs();
		this.rl = new LineEditor({
			prompt: '(xsdb) ',
			completer: (line, callback) => {
				const m = this.getMachine(this.activeThreadId);
				if (m && typeof m.completer === 'function')
					m.completer(line, callback);
				else
					callback(null, [[], line]);
			}
		});

		this.rl.onLine = (line) => {
			const active = this.getMachine(this.activeThreadId);
			if (active) active.promptShown = false;

			const str = line.trim();
			if (str === 'set mcsim on' || str === 'set mcsim off') {
				this.showMcsim = str === 'set mcsim on';
				this.savePrefs();
				if (active) {
					active.report('set', { showMcsim: this.showMcsim }, undefined, () => {
						console.log(`mcsim thread: ${this.showMcsim ? 'on' : 'off'}`);
						active.showPrompt();
					});
				} else {
					console.log(`mcsim thread: ${this.showMcsim ? 'on' : 'off'}`);
				}
				return;
			}
			if (str.startsWith('info threads')) {
				const threadsData = this.machines.map(m => {
					if (!m) return null;
					if (m.id === undefined) return null;
					if (this.isHidden(m)) return null;
					return {
						id: m.id,
						active: m.id === this.activeThreadId,
						name: m.title || `worker-${m.id}`,
						state: !m.connected ? 'Disconnected' : (m.running ? 'Running' : 'Stopped'),
						path: (!m.connected || m.running) ? undefined : (m.currentPath || 'unknown'),
						line: (!m.connected || m.running) ? undefined : (m.currentLine || '?')
					};
				}).filter(Boolean);

				if (active) {
					active.currentCommand = 'info_threads';
					active.report('info_threads', { threads: threadsData }, undefined, (data) => {
						console.log('  Id   Name               State');
						data.threads.forEach(t => {
							const sel = t.active ? '*' : ' ';
							const stateStr = t.state === 'Stopped' ? `Stopped at ${t.path}:${t.line}` : t.state;
							console.log(`${sel} ${t.id.toString().padEnd(4)} ${t.name.padEnd(18)} ${stateStr}`);
						});
					});
					active.showPrompt();
				} else {
					console.log('  Id   Name               State');
					threadsData.forEach(t => {
						const sel = t.active ? '*' : ' ';
						const stateStr = t.state === 'Stopped' ? `Stopped at ${t.path}:${t.line}` : t.state;
						console.log(`${sel} ${t.id.toString().padEnd(4)} ${t.name.padEnd(18)} ${stateStr}`);
					});
				}
				return;
			}
			const isThreadApply = str === 'thread apply' || str.startsWith('thread apply ') || str === 't apply' || str.startsWith('t apply ');
			if (isThreadApply) {
				const prefixLen = str.startsWith('t apply') ? 7 : 12;
				const args = str.substring(prefixLen).trim();
				if (args.startsWith('all ')) {
					const cmd = args.substring(4).trim();
					this.machines.forEach(m => {
						if (!m) return;
						if (m.id === undefined) return;
						if (this.isHidden(m)) return;
						const name = m.title || `worker-${m.id}`;
						console.log(`Thread ${m.id} (${name}):`);
						m.handleCommand(cmd);
					});
				} else {
					const match = args.match(/^([\d\s]+)\s+(.+)$/);
					if (match) {
						const ids = match[1].split(/\s+/).map(x => parseInt(x));
						const cmd = match[2];
						ids.forEach(id => {
							const m = this.getMachine(id);
							if (m) {
								const name = m.title || `worker-${id}`;
								console.log(`Thread ${id} (${name}):`);
								m.handleCommand(cmd);
							} else if (active) {
								active.currentCommand = 'thread';
								active.commandError(`Thread ID ${id} not known.`);
							}
						});
					} else if (active) {
						active.currentCommand = 'thread';
						active.commandError('Usage: thread apply [all | <id1> <id2>...] <command>');
					}
				}
				if (active) active.showPrompt();
				return;
			}
			if (str === 'thread' || str === 't' || str.startsWith('thread ') || str.startsWith('t ')) {
				const match = str.match(/^(?:thread|t)\s+(\d+)$/);
				if (match) {
					const id = parseInt(match[1]);
					const m = this.getMachine(id);
					if (m && this.isHidden(m)) {
						if (active) {
							active.currentCommand = 'thread';
							active.commandError(`Thread ${id} is hidden (mcsim). Use "set mcsim on" to show.`);
							active.showPrompt();
						}
					} else if (m) {
						this.activeThreadId = id;
						m._clearLineGlobal();
						const name = m.title || `worker-${id}`;
						m.currentCommand = 'thread';
						m.report('thread', { id, name }, undefined, (data) => {
							console.log(`[Switching to thread ${data.id} (${data.name})]`);
						});
						if (!m.running) m.printLocation();
						m.showPrompt();
					} else {
						if (active) {
							active.currentCommand = 'thread';
							active.commandError(`Thread ID ${id} not known.`);
						}
					}
				} else {
					if (active) {
						active.currentCommand = 'thread';
						active.commandError('Usage: thread <id>');
					}
				}
				return;
			}

			if (str === 'quit' || str === 'q') {
				if (active)
					active.handleCommand(str);
				else
					Host.exit(0);
				return;
			}

			if (active)
				active.handleCommand(str);
			else {
				console.log('No active connection. Waiting for device...');
				this.rl.prompt(true);
			}
		};

		this.rl.onClose = () => {
			if (!Host.isTTY()) return;
			this.machines.forEach(m => {
				if (m && m.connected) m.doAbort();
			});
			Host.exit(0);
		};

		this.rl.onInterrupt = () => {
			const active = this.getMachine(this.activeThreadId);
			if (active) {
				if (active.running) active.doStep();
				else {
					console.log('Use "quit" to exit.');
					active.promptShown = false;
					active.showPrompt();
				}
			}
			else {
				console.log('No active connection. Use "quit" to exit.');
				this.rl.prompt(true);
			}
		};

		this.rl.start();
	},

	addMachine(target) {
		if (!this.rl) this.init();

		const m = new LogMachine(target);

		// Map router extensions cleanly into the Machine so it interfaces with the global rl natively.
		m.rl = this.rl;
		m._clearLineGlobal = () => {
			if (m.promptShown) {
				this.rl.write('\x1B[2K\x1B[0G');
				m.promptShown = false;
			}
		};
		// Override Machine's clearLine natively
		m.clearLine = m._clearLineGlobal;

		if (!this.globalBreakpoints) this.globalBreakpoints = [];
		m.breakpoints = this.globalBreakpoints;
		m.getNextBreakpointId = () => {
			return ++this.globalBreakpointIdCounter;
		};

		// Broadcast breakpoint changes to all connected machines.
		const baseDoSetBreakpoint = Machine.prototype.doSetBreakpoint;
		const baseDoClearBreakpoint = Machine.prototype.doClearBreakpoint;
		const baseDoClearAllBreakpoints = Machine.prototype.doClearAllBreakpoints;

		m.doSetBreakpoint = (path, line, options) => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoSetBreakpoint.call(mach, path, line, options);
			});
		};

		m.doClearBreakpoint = (path, line) => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoClearBreakpoint.call(mach, path, line);
			});
		};

		m.doClearAllBreakpoints = () => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoClearAllBreakpoints.call(mach);
			});
		};

		m.outputFormat = this.globalOutputFormat;
		m.exceptionsMode = this.globalExceptionsMode;
		m.breakOnStart = this.globalBreakOnStart;
		m.timestamps = this.globalTimestamps;
		const originalCmdSet = m.cmdSet.bind(m);
		m.cmdSet = (args) => {
			originalCmdSet(args);
			let save = false;
			if (args[0] === 'output') { this.globalOutputFormat = m.outputFormat; save = true; }
			if (args[0] === 'exceptions') { this.globalExceptionsMode = m.exceptionsMode; save = true; }
			if (args[0] === 'start') { this.globalBreakOnStart = m.breakOnStart; save = true; }
			if (args[0] === 'timestamps' || args[0] === 'timestamp') { this.globalTimestamps = m.timestamps; save = true; }
			if (save) {
				this.machines.forEach(mach => {
					if (mach && mach !== m) {
						mach.outputFormat = this.globalOutputFormat;
						mach.exceptionsMode = this.globalExceptionsMode;
						mach.breakOnStart = this.globalBreakOnStart;
						mach.timestamps = this.globalTimestamps;
					}
				});
				this.savePrefs();
			}
		};

		for (const name of ['cmdBreak', 'cmdClear', 'cmdDelete', 'cmdCondition', 'cmdTrace', 'cmdHitcount']) {
			const original = m[name].bind(m);
			m[name] = (args) => {
				original(args);
				this.savePrefs();
			};
		}

		this.machines.push(m);
		m.onBreakpointHit = () => {
			if (this.isHidden(m)) return;
			if (this.activeThreadId !== m.id) {
				if (m.outputFormat !== 'json') {
					m._clearLineGlobal();
					const name = m.title || `worker-${m.id}`;
					console.log(`\n[Switching to thread ${m.id} (${name})]`);
				}
				this.activeThreadId = m.id;
			}
		};
		m.onTitleReady = () => {
			if (m.interactive) {
				m.id = this.nextThreadId++;
			} else {
				m.id = 0;
			}
			const activeMach = this.getMachine(this.activeThreadId);
			if (!this.isHidden(m) && (!activeMach || this.isHidden(activeMach)))
				this.activeThreadId = m.id;
		};
		return m;
	}
};

function onConnection(target) {
	connections++;

	const machine = xsdbRouter.addMachine(target);
	machine.onError = (error, message) => {
		if (message !== undefined)
			console.log(`#xsdb bad message from "${machine.title ?? "?"}": ${error.message}`);
	};
	machine.onClose = (reason) => {
		if ((Socket.error === reason) && machine.title)
			console.log(`#xsdb socket error for "${machine.title}"`);
		if (machine.title && ("mcsim" !== machine.title))
			machine.print(`#xsdb disconnected from "${machine.title}"`);

		const isDyingActive = (xsdbRouter.activeThreadId === machine.id);

		const idx = xsdbRouter.machines.indexOf(machine);
		if (idx !== -1) xsdbRouter.machines[idx] = null;

		if (isDyingActive) {
			xsdbRouter.activeThreadId = 0;
			const fallback = xsdbRouter.machines.find(m => m && !xsdbRouter.isHidden(m));
			if (fallback)
				xsdbRouter.activeThreadId = fallback.id;
			else if (xsdbRouter.rl)
				xsdbRouter.rl.prompt(true);
		}

		if (!xsdbRouter.machines.some(m => m))
			xsdbRouter.nextThreadId = 1;

		try {
			target.close();
		} catch (e) {}

		if ((0 === --connections) && autoexit)
			Host.exit(0);
	};
}

// the listener, or null when another process holds the port
function listen() {
	try {
		return new Listener({ port: portIn });
	}
	catch (e) {
		return null;
	}
}

function launch(listener) {
	listener.callback = function() {
		onConnection(new Socket({ listener }));
	};
	console.log(`xsdb listening on port ${portIn}. Type "quit" to exit.`);
	if (!xsdbRouter.rl)
		xsdbRouter.init();

	let args = Host.arguments.slice(1);
	if (args.length === 0) {
		console.log("xsdb: no command line arguments. Waiting for connection.");
		return;
	}

	// Intercept OS-detaching execution hooks
	if (args.length >= 2 && args[0] === 'open' && (args[1] === '-a' || args[1] === '-W')) {
		args = args.slice(2);
		// Remap macOS .app bundles to their internal WindowServer binary
		if (args[0] && args[0].endsWith('.app')) {
			const appName = args[0].split('/').pop().replace('.app', '');
			let binaryPath = `${args[0]}/Contents/MacOS/${appName}`;
			if (!File.exists(binaryPath)) {
				binaryPath = `${args[0]}/Contents/MacOS/main`;
			}
			if (File.exists(binaryPath)) {
				args[0] = binaryPath;
			}
		}
	} else if (args.length >= 2 && args[0] === 'start' && args[1] === '/B') {
		args = args.slice(2);
	}

	// In the extremely rare event all arguments were stripped, abort.
	if (args.length === 0) return;

	try {
		const targetBin = args[0];
		const targetArgs = args.slice(1);

		// The child gets no stdin so it cannot take the terminal from the line editor, and its stdout
		// is dropped so raw C logs don't double-print over the traces parsed from the connection.
		Host.setChildExit((pid, code) => {
			if (pid !== child)
				return;
			child = null;
			if (connections === 0 && autoexit) {
				console.log(`\n#xsdb simulator cleanly executed or terminated before connecting. Exiting.`);
				Host.exit(code || 0);
			}
		});
		child = Host.spawn(targetBin, targetArgs, "ignore");
	} catch (e) {
		console.log(`#xsdb explicit spawn exception: ${e.message}`);
	}
}

let listener = listen();
if (listener)
	launch(listener);
else {
	const rl = new LineEditor();
	rl.start();
	rl.question(`xsdb: Port ${portIn} is already in use (app or instance running).\nForcefully terminate the app holding the port? (y / n) `, (answer) => {
		rl.close();
		if (answer.trim().toLowerCase().startsWith('y')) {
			try {
				if (Host.platform === "win")
					Host.execute("cmd", ["/c", `FOR /F "tokens=5" %P IN ('netstat -ano ^| findstr :${portIn}') DO taskkill /PID %P /F`], 5000);
				else
					Host.execute("sh", ["-c", `kill -9 $(lsof -t -i :${portIn})`], 5000);
			}
			catch (e) {
				console.log(`xsdb: could not stop the process holding port ${portIn}: ${e.message}`);
			}
			Timer.set(() => {
				listener = listen();
				if (listener)
					launch(listener);
				else {
					console.log(`xsdb: Port ${portIn} is still in use. Exiting.`);
					Host.exit(-1);
				}
			}, 500);
		} else {
			console.log('Exiting.');
			Host.exit(-1);
		}
	});
}
